Repository rdkcentral/rdk-halif-test-device_settings, pull requests merged in 2024-08, with the labels that each got.

#114 Audio test profile modifications
  src/test_l1_dsAudio.c
Labels: L1 related issues

#73 gh #64 Test profile changes for HdmiIn
  profiles/sink/Sink_HDMIIN.yaml
  src/test_l1_dsHdmiIn.c
Labels: L1 related issues

#113 gh #67 Test profile changes for dsFPD
  src/test_l1_dsFPD.c
Labels: L1 related issues

#122 gh #107 Code Cleanup of CompositeIn
  src/test_l1_dsCompositeIn.c
Labels: L1 related issues

#127 gh #126 Updating source yaml file for display
  profiles/source/Source_4K_Display.yaml
Labels: L1 related issues

#119 gh #105 host code cleanup
  src/test_l1_dsHost.c
Labels: L1 related issues

#125 gh #111 Code Cleanup of dsVideoDevice
  src/test_dsVideoDevice_parse_configuration.c
  src/test_dsVideoDevice_parse_configuration.h
  src/test_l1_dsVideoDevice.c
Labels: L1 related issues

#118 gh #108 L1 videoport code cleanup
  src/test_dsVideoPort_parse_configuration.c
  src/test_dsVideoPort_parse_configuration.h
  src/test_l1_dsVideoPort.c
Labels: L1 related issues

#128 gh #109 code clean up for audio
  src/test_l1_dsAudio.c
Labels: L1 related issues

#124 gh #110 Code Cleanup of dsHdmiIn
  src/test_l1_dsHdmiIn.c
Labels: L1 related issues

#130 gh #112 code cleanup of dsFPD
  src/test_l1_dsFPD.c
Labels: L1 related issues

#95 gh #94 Wrong size for Profile file string parsing
  src/test_dsAudio_parse_configuration.c
Labels: L1 related issues, L2 related issues

#132 gh #131 added run script & Updated README.md
  README.md
  bin/run.sh
Labels: bug

#134 FIx Logic for setFPColor and getFP Color
  profiles/sink/Sink_FPD.yaml
  profiles/source/Source_FPD.yaml
  src/test_l1_dsFPD.c
  src/test_l2_dsFPD.c
Labels: bug

#136 Corrected the kvp function to read number of indicators
  src/test_l2_dsFPD.c
Labels: bug, L2 related issues
