Repository rdkcentral/rdk-halif-test-device_settings, pull requests merged in 2024-06, with the labels that each got.

#45 deviceSettings: Enhanced Error code for device settings
  profiles/deviceSettingsExtendedEnumsNotSupported.yaml
  src/test_l1_dsAudio.c
  src/test_l1_dsDisplay.c
  src/test_l1_dsHdmiIn.c
  src/test_l1_dsHost.c
  src/test_l1_dsVideoDevice.c
  src/test_l1_dsVideoPort.c
Labels: bug

#47 Composite HL Spec -YAML changes and Spec changes
  docs/pages/ds-compositeIn-High-Level_TestSpec.md
  docs/pages/ds-compositeIn-L2-Low-Level_TestSpec.md
  docs/pages/dsComposite_test_spec.md
  profiles/sink/Panel_CompositeInput.yaml
  src/test_l2_dsCompositeIn.c
Labels: L2 Work Element

#9 gh #7 updating the dsHost test specification and the code
  docs/pages/ds-host_High-Level_TestSpecification.md
  docs/pages/ds-host_L2_Low-Level_TestSpecification.md
  docs/pages/dsDisplay_TestSpecificaion.md
  profiles/deviceSettingsExtendedEnumsNotSupported.yaml
  profiles/sink/Sink_HostSettings.yaml
  profiles/source/Source_HostSettings.yaml
  src/test_l2_dsHost.c
  src/test_register.c
Labels: L2 Work Element

#48 DS Display HL changes and YAML changes
  docs/pages/ds-display-L2-Low-Level_TestSpec.md
  docs/pages/ds-display-high-Level_TestSpec.md
  profiles/sink/Panel_4K_Display.yaml
  profiles/source/Puck_4K_Display.yaml
  src/test_l2_dsDisplay.c
Labels: L2 Work Element

#32 High Level spec for Device Settings HDMI input
  docs/pages/ds-hdmi-in-High-Level_TestSpec.md
  docs/pages/ds-hdmi-in-L2-Low-Level_TestSpec.md
  profiles/sink/Sink_HDMIIN.yaml
  profiles/source/Source_HDMIIN.yaml
  src/test_l2_dsHdmiIn.c
Labels: L2 Work Element

#20 dsVideoDevice High Level Test Specification Documentation
  build.sh
  docs/pages/ds-video-device_High-Level_TestSpec.md
  docs/pages/ds-video-device_L2-Low-Level_TestSpec.md
  profiles/sink/Sink_VideoDevice.yaml
  profiles/source/Source_VideoDevice.yaml
  src/test_dsVideoDevice_parse_configuration.c
  src/test_dsVideoDevice_parse_configuration.h
  src/test_l2_dsVideoDevice.c
  src/test_register.c
Labels: documentation

#15 dsVideoPort High Level Test Specification Documentation
  bin/run.sh
  docs/pages/ds-video-port_High-Level_TestSpec.md
  docs/pages/ds-video-port_L2_Low-Level_TestSpecification.md
  profiles/sink/Sink_4K_VideoPort.yaml
  profiles/source/Source_4K_VideoPort.yaml
  src/test_dsAudio_parse_configuration.c
  src/test_dsVideoDevice_parse_configuration.c
  src/test_dsVideoPort_parse_configuration.c
  src/test_dsVideoPort_parse_configuration.h
  src/test_l2_dsAudio.c
  src/test_l2_dsDisplay.c
  src/test_l2_dsHost.c
  src/test_l2_dsVideoDevice.c
  src/test_l2_dsVideoPort.c
  src/test_parse_configuration.c
  src/test_parse_configuration.h
Labels: documentation, enhancement, L2 Work Element

#33 Feature/issue23 ds fp test spec
  docs/pages/ds-front-panel-display_High-Level_TestSpec.md
  docs/pages/ds-front-panel-display_L2_Low-Level_TestSpecification.md
  profiles/sink/Sink_FPD.yaml
  profiles/source/Source_FPD.yaml
  src/test_l2_dsFPD.c
Labels: documentation

#77 gh #76 Updated L2 code, README.md,doxygen
  README.md
  profiles/sink/Sink_4K_Display.yaml
  profiles/sink/Sink_CompositeInput.yaml
  profiles/source/Source_4K_Display.yaml
  src/test_dsAudio_parse_configuration.c
  src/test_dsAudio_parse_configuration.h
  src/test_dsVideoDevice_parse_configuration.c
  src/test_dsVideoDevice_parse_configuration.h
  src/test_dsVideoPort_parse_configuration.c
  src/test_dsVideoPort_parse_configuration.h
  src/test_l2_dsAudio.c
  src/test_l2_dsCompositeIn.c
  src/test_l2_dsFPD.c
  src/test_l2_dsHdmiIn.c
  src/test_l2_dsVideoPort.c
Labels: documentation, enhancement, L2 Work Element

#79 gh #78 update flag for source and sink
  src/test_l2_dsDisplay.c
Labels: bug, L2 Work Element
