Repository rdkcentral/rdk-halif-test-device_settings, pull requests merged in 2024-10, with the labels that each got.

#189 VideoPort Updated L3 python Overview
  docs/pages/ds-video-port_L3_Low-Level_TestSpecification.md
  docs/pages/dsVideoPort/ds-video-port_L3_Low-Level_TestSpecification.md
  host/tests/dsClasses/dsVideoPort_test_suite.yml
  host/tests/dsVideoPort_L3_Tests/dsVideoPort_L3_testSetup.yml
Labels: documentation, L3 Work Element

#174 GH #173 L3 ds composite-In Low level Test specification and procedure document
  docs/pages/dsCompositeIn/ds-compositeIn-High-Level_TestSpec.md
  docs/pages/dsCompositeIn/ds-compositeIn-L2-Low-Level_TestSpec.md
  docs/pages/dsCompositeIn/ds-compositeIn-L3-Low-Level-TestSpec.md
  host/tests/dsClasses/dsCompositeIn_test_suite.yml
  host/tests/dsCompositeIn_L3_Tests/dsCompositeIn_L3_testSetup.yml
Labels: documentation, L3 Work Element

#178 GH#171 ds hdmi in l3 highlevl spec
  docs/pages/dsHDMIIn/ds-Hdmi-In_L3_Low-Level_TestSpecification.md
  docs/pages/dsHDMIIn/ds-hdmi-in-High-Level_TestSpec.md
  docs/pages/dsHDMIIn/ds-hdmi-in-L2-Low-Level_TestSpec.md
  host/tests/dsClasses/dsHdmiIn_test_suite.yml
  host/tests/dsHdmiIn_L3_Tests/dsHdmiIn_L3_testSetup.yml
Labels: documentation, L3 Work Element

#180 gh #179 l3 ds video device test doc
  docs/pages/dsVideoDevice/ds-video-device_High-Level_TestSpec.md
  docs/pages/dsVideoDevice/ds-video-device_L2-Low-Level_TestSpec.md
  docs/pages/dsVideoDevice/ds-video-device_L3_Low-Level_TestSpecification.md
  host/tests/dsClasses/dsVideoDevice_test_suite.yml
  host/tests/dsVideoDevice_L3_Tests/dsVideoDevice_L3_testSetup.yml
Labels: documentation, L3 Work Element

#176 GH#175 Test Spec Document - FPD L3
  docs/pages/dsFPD/ds-front-panel-display_High-Level_TestSpec.md
  docs/pages/dsFPD/ds-front-panel-display_L2_Low-Level_TestSpecification.md
  docs/pages/dsFPD/ds-front-panel-display_L3_Low-Level_TestSpecification.md
  host/tests/dsClasses/dsFPD_test_suite.yml
  host/tests/dsFPD_L3_Tests/dsFPD_L3_testSetup.yml
Labels: documentation, L3 Work Element

#170 GH #169 dsDisplay : L3 Low level Test specification
  docs/pages/dsDisplay/ds-display-L2-Low-Level_TestSpec.md
  docs/pages/dsDisplay/ds-display-high-Level_TestSpec.md
  docs/pages/dsDisplay/ds-display_L3_Low-Level_TestSpecification.md
  host/tests/dsClasses/dsDisplay_test_suite.yml
  host/tests/dsDisplay_L3_Tests/dsDisplay_L3_testSetup.yml
Labels: documentation, L3 Work Element

#156 gh #154 VTS - L3 dsCompisiteIn C-Test Spec and Code Implementation
  src/main.c
  src/test_l3_dsCompositeIn.c
  src/test_register.c
Labels: L3 Work Element

#152 gh #150 dsDisplay L3 Test case Development
  src/test_l3_dsDisplay.c
  src/test_register.c
Labels: L3 Work Element

#149 GH#145 HdmiIn l3 testcases implementation
  src/test_l3_dsHdmiIn.c
  src/test_register.c
Labels: L3 Work Element

#155 gh #151 - FPD L3 C Test
  src/test_l3_dsFPD.c
  src/test_register.c
Labels: L3 Work Element

#204 GH# 203 l3 linkingissue fix
  src/test_l3_dsCompositeIn.c
  src/test_l3_dsHdmiIn.c
Labels: bug, L3 Work Element

#153 gh#148 dsVideoDevice L3 test suit code
  src/test_l3_dsVideoDevice.c
  src/test_register.c
Labels: enhancement, L3 Work Element

#185 GH #184: dsFPD get led state test step update
  src/test_l1_dsFPD.c
Labels: bug

#213 issue211 l1 issuefix dsDisplay
  src/test_l1_dsDisplay.c
Labels: bug

#214 gh #212: dsFPD L1 issuefix
  src/test_l1_dsFPD.c
Labels: bug

#187 gh #186: dsAudio L3 developement code
  docs/pages/dsAudio/ds-audio_L3_Low-Level_TestSpecification.md
  host/tests/L3_TestCases/dsAudio/dsAudio_L3_testSetup.yml
  host/tests/L3_TestCases/dsAudio/dsAudio_test01_EnableDisableAndVerifyAudioPortStatus.py
  host/tests/L3_TestCases/dsAudio/dsAudio_test02_PortConnectionStatus.py
  host/tests/L3_TestCases/dsAudio/dsAudio_test03_MS12AudioCompression.py
  host/tests/L3_TestCases/dsAudio/dsAudio_test04_MS12DialogueEnhancer.py
  host/tests/L3_TestCases/dsAudio/dsAudio_test05_MS12DolbyVolume.py
  host/tests/L3_TestCases/dsAudio/dsAudio_test06_MS12IntelligentEqualizer.py
  host/tests/L3_TestCases/dsAudio/dsAudio_test07_MS12Volumeleveller.py
  host/tests/L3_TestCases/dsAudio/dsAudio_test08_MS12BassEnhancer.py
  host/tests/L3_TestCases/dsAudio/dsAudio_test09_MS12SurroundDecoder.py
  host/tests/L3_TestCases/dsAudio/dsAudio_test10_MS12DRCMode.py
  host/tests/L3_TestCases/dsAudio/dsAudio_test11_MS12SurroundVirtualizer.py
  host/tests/L3_TestCases/dsAudio/dsAudio_test12_MS12MISteering.py
  host/tests/L3_TestCases/dsAudio/dsAudio_test13_MS12GraphicEqualizer.py
  host/tests/L3_TestCases/dsAudio/dsAudio_test14_MS12LEConfig.py
  host/tests/L3_TestCases/dsAudio/dsAudio_test15_ARCPort.py
  host/tests/L3_TestCases/dsAudio/dsAudio_test16_ARCSAD.py
  host/tests/L3_TestCases/dsAudio/dsAudio_test17_OutputMode.py
  host/tests/L3_TestCases/dsAudio/dsAudio_test18_AudioLevel.py
  host/tests/L3_TestCases/dsAudio/dsAudio_test19_SpeakerAudioGain.py
  host/tests/L3_TestCases/dsAudio/dsAudio_test20_MuteUnMute.py
  host/tests/L3_TestCases/dsAudio/dsAudio_test21_AudioDelay.py
  host/tests/L3_TestCases/dsAudio/dsAudio_test22_AudioFormat.py
  host/tests/L3_TestCases/dsAudio/dsAudio_test23_AssociateMix.py
  host/tests/L3_TestCases/dsAudio/dsAudio_test24_PrimarySecondaryLanguage.py
  host/tests/L3_TestCases/dsAudio/dsAudio_test25_AudioMix.py
  host/tests/L3_TestCases/dsAudio/dsAudio_test26_MS12AudioProfiles.py
  host/tests/configs/deviceConfig.yml
  host/tests/configs/example_rack_config.yml
  host/tests/dsAudio_L3_Tests/dsAudio_L3_testSetup.yml
  host/tests/dsClasses/dsAudio.py
  host/tests/dsClasses/dsAudio_test_suite.yml
  profiles/sink/Sink_AudioSettings.yaml
  profiles/source/Source_AudioSettings.yaml
  src/main.c
  src/test_l3_dsAudio.c
  src/test_parse_configuration.c
  src/test_register.c
Labels: L3 Work Element

#196 gh #190 dsvideo port l3 C and Python testcase Implementation
  docs/pages/dsVideoPort/ds-video-port_L3_Low-Level_TestSpecification.md
  host/.vscode/launch.json
  host/tests/L3_TestCases/dsVideoPort/dsVideoPort_L3_testSetup.yml
  host/tests/L3_TestCases/dsVideoPort/dsVideoPort_test1_VerifyVideoContent_Format_Callback.py
  host/tests/L3_TestCases/dsVideoPort/dsVideoPort_test2_EnableDisableAndVerifyPortStatus.py
  host/tests/L3_TestCases/dsVideoPort/dsVideoPort_test3_VerifyHDCP_Version.py
  host/tests/L3_TestCases/dsVideoPort/dsVideoPort_test4_VerifyResolution.py
  host/tests/L3_TestCases/dsVideoPort/dsVideoPort_test5_VerifyHDCP_Callback.py
  host/tests/L3_TestCases/dsVideoPort/dsVideoPort_test6_VerifyVideoContentFormats.py
  host/tests/L3_TestCases/dsVideoPort/dsVideoPort_test7_ResetToSDRMode.py
  host/tests/L3_TestCases/dsVideoPort/dsVideoPort_test8_VerifyColorDepth.py
  host/tests/L3_TestCases/dsVideoPort/dsVideoPort_test9_VerifyBackgroundColor.py
  host/tests/configs/deviceConfig.yml
  host/tests/dsClasses/dsVideoPort.py
  host/tests/dsClasses/dsVideoPort_test_suite.yml
  host/tests/dsVideoPort_L3_Tests/dsVideoPort_L3_testSetup.yml
  profiles/sink/Sink_4K_VideoPort.yaml
  profiles/source/Source_4K_VideoPort.yaml
  src/test_l3_dsVideoPort.c
Labels: enhancement, L3 Work Element

#225 dsVideoPort L3 test procedure documentation
  docs/pages/dsVideoPort/ds-video-port_L3_Low-Level_TestSpecification.md
  docs/pages/dsVideoPort/ds-video-port_L3_Test-Procedure.md
Labels: L3 Work Element

#221 gh #220: dsAudio L3 Test Procedure document
  docs/pages/dsAudio/ds-audio_L3_Low-Level_TestSpecification.md
  docs/pages/dsAudio/ds-audio_L3_TestProcedure.md
Labels: documentation, L3 Work Element

#228 Feature/gh226 ds audio update python tests
  host/tests/L3_TestCases/dsAudio/dsAudio_test07_MS12Volumeleveller.py
  host/tests/L3_TestCases/dsAudio/dsAudio_test21_AudioDelay.py
Labels: bug, L3 Work Element

#193 Feature/192 makefile upgrade correcting clean and framework make
  .gitignore
  Makefile
  build.sh
Labels: bug
