Repository rdkcentral/rdk-halif-test-device_settings, pull requests merged in 2024-09, with the labels that each got.

#144 gh #143 Added supported Resolutions for Source device profile
  profiles/source/Source_4K_VideoPort.yaml
  src/test_l2_dsVideoPort.c
Labels: L1 related issues, L2 related issues

#161 gh #160: Initial python setup layout
  host/.gitignore
  host/.vscode/launch.json
  host/activate_venv.sh
  host/install.sh
  host/tests/.gitignore
  host/tests/configs/.gitignore
  host/tests/configs/deviceConfig.yml
  host/tests/configs/example_rack_config.yml
Labels: L3 Work Element

#163 gh #162: Add helpers folder to python
  host/tests/helpers/testHelper.py
Labels: L3 Work Element

#142 L1 Profile update issue fixes
  docs/pages/ds-video-device_L2-Low-Level_TestSpec.md
  profiles/sink/Sink_2K_VideoDevice.yaml
  profiles/sink/Sink_4K_VideoDevice.yaml
  src/test_dsVideoDevice_parse_configuration.c
  src/test_dsVideoDevice_parse_configuration.h
  src/test_l1_dsVideoDevice.c
  src/test_l2_dsVideoDevice.c
Labels: bug, enhancement

#166 UT_ASSERT update for sting Comparison
  src/test_l1_dsAudio.c
  src/test_l1_dsDisplay.c
  src/test_l1_dsHdmiIn.c
Labels: bug, L2 related issues

#103 dsVideoPort L3 low-level Spec & implementation
  README.md
  docs/pages/dsVideoPort/ds-video-port_High-Level_TestSpec.md
  docs/pages/dsVideoPort/ds-video-port_L2_Low-Level_TestSpecification.md
  docs/pages/dsVideoPort/ds-video-port_L3_Low-Level_TestSpecification.md
  src/main.c
  src/test_l3_dsVideoPort.c
  src/test_register.c
Labels: L3 Work Element

#102 gh #101 dsAudio: L3 Low level Test specification and procedure document
  docs/pages/dsAudio/ds-audio_High-Level_TestSpecification.md
  docs/pages/dsAudio/ds-audio_L2_Low-Level_TestSpecification.md
  docs/pages/dsAudio/ds-audio_L3_Low-Level_TestSpecification.md
Labels: L3 Work Element

#116 gh #115 dsAudio: L3 Test case Development
  src/main.c
  src/test_l3_dsAudio.c
  src/test_parse_configuration.c
  src/test_register.c
Labels: L3 Work Element

#182 gh #181: L3 C Test: Issues after merging dsAudio dsVideo
  README.md
  src/main.c
  src/test_l3_dsAudio.c
  src/test_l3_dsVideoPort.c
Labels: L3 Work Element

#164 gh #159: dsAudio L3 Python test code
  .gitignore
  .vscode/c_cpp_properties.json
  .vscode/launch.json
  .vscode/tasks.json
  bin/run.sh
  docs/pages/ds-video-port_L3_Low-Level_TestSpecification.md
  docs/pages/dsAudio/ds-audio_L3_Low-Level_TestSpecification.md
  host/.vscode/launch.json
  host/install.sh
  host/tests/configs/deviceConfig.yml
  host/tests/configs/example_rack_config.yml
  host/tests/dsAudio_L3_Tests/dsAudio_L3_testSetup.yml
  host/tests/dsAudio_L3_Tests/dsAudio_test1_EnableDisableAndVerifyAudioPortStatus.py
  host/tests/dsClasses/dsAudio.py
  host/tests/dsClasses/dsAudio_test_suite.yml
  host/tests/helpers/testHelper.py
  src/main.c
  src/test_dsAudio_parse_configuration.c
  src/test_dsAudio_parse_configuration.h
  src/test_dsVideoDevice_parse_configuration.c
  src/test_dsVideoDevice_parse_configuration.h
  src/test_dsVideoPort_parse_configuration.h
  src/test_l1_dsAudio.c
  src/test_l3_dsAudio.c
  src/test_l3_dsVideoPort.c
  src/test_parse_configuration.c
  src/test_parse_configuration.h
  src/test_register.c
  ut.code-workspace
Labels: enhancement, L3 Work Element
