Repository rdkcentral/rdk-halif-test-device_settings, pull requests merged in 2024-12, with the labels that each got.

#273 gh #272 change the correct value for bitwise operation
  src/test_l1_dsAudio.c
Labels: bug, L1 related issues

#278 gh #227 updated Make file with target=linux
  Makefile
Labels: bug

#271 gh #270 dsFPD L3 issue fix
  host/tests/L3_TestCases/dsFPD/dsFPD_test04_SetVerifyLEDIndicatorsColor.py
  host/tests/dsClasses/dsFPD_testConfig.yml
Labels: bug, L3 Work Element

#147 gh #137 dshdmi in l1 l2 dsGetHdmiVersion
  docs/pages/dsHDMIIn/ds-hdmi-in-High-Level_TestSpec.md
  docs/pages/dsHDMIIn/ds-hdmi-in-L2-Low-Level_TestSpec.md
  profiles/sink/Sink_HDMIIN.yaml
  profiles/source/Source_HDMIIN.yaml
  skeletons/src/dsHdmiIn.c
  src/test_l1_dsHdmiIn.c
  src/test_l2_dsHdmiIn.c
Labels: New API Test

#269 gh #268 CompositeIn L3 testcase for new API
  docs/pages/dsCompositeIn/ds-compositeIn-L3-Low-Level-TestSpec.md
  docs/pages/dsCompositeIn/ds-compositeIn-L3-TestProcedure.md
  host/tests/L3_TestCases/dsCompositeIn/dsCompositeIn_L3_testSetup.yml
  host/tests/L3_TestCases/dsCompositeIn/dsCompositeIn_test5_VerifyVideoMode_Callback.py
  host/tests/dsClasses/dsCompositeIn.py
  src/test_l3_dsCompositeIn.c
Labels: IF Updates, L3 Work Element

#281 gh #280 Updated profile,testcase for Dialog Enhancement
  host/tests/L3_TestCases/dsAudio/dsAudio_test04_MS12DialogueEnhancer.py
  host/tests/dsClasses/dsAudio.py
  profiles/sink/Sink_4K_VideoPort.yaml
  profiles/sink/Sink_AudioSettings.yaml
  profiles/source/Source_4K_VideoPort.yaml
  profiles/source/Source_AudioSettings.yaml
  src/test_dsAudio_parse_configuration.c
  src/test_dsAudio_parse_configuration.h
  src/test_dsVideoDevice_parse_configuration.c
  src/test_l1_dsAudio.c
  src/test_l2_dsAudio.c
Labels: bug, L1 related issues, L2 related issues, L3 Work Element
