Repository rdkcentral/rdk-halif-test-device_settings, pull requests merged in 2024-11, with the labels that each got.

#237 VTS L1- SoC Vendor Issues - dsHdmiIn L1 Issue Fix.
  src/test_l1_dsHdmiIn.c
Labels: bug, L1 related issues

#218 gh #217 L1 dsVideoDevice Issue fix
  src/test_l1_dsVideoDevice.c
Labels: bug, L1 related issues

#231 gh #229 VTS - L1 Issue fix - SoC Vendor Issues - dsVideoPort
  profiles/sink/Sink_4K_VideoPort.yaml
  profiles/source/Source_4K_VideoPort.yaml
  src/test_l1_dsVideoPort.c
Labels: bug, L1 related issues

#232 gh #230 L1 Issue fixes - dsAudio
  src/test_l1_dsAudio.c
Labels: bug, L1 related issues

#240 gh #239 Updated the install script with ut_raft tag
  host/install.sh
Labels: enhancement

#206 gh #205 dsHost L3 Python Test Cases
  docs/pages/dsHost/ds-host_L3_TestProcedure.md
  host/tests/L3_TestCases/dsHost/dsHost_L3_testSetup.yml
  host/tests/L3_TestCases/dsHost/dsHost_test1_VerifyTemperature.py
  host/tests/dsClasses/dsHost.py
  host/tests/dsClasses/dsHost_test_suite.yml
  src/test_l3_dsHost.c
Labels: L3 Work Element

#210 GH #199 dsCompositeIn L3 Python Test code
  docs/pages/dsCompositeIn/ds-compositeIn-L3-TestProcedure.md
  host/tests/L3_TestCases/dsCompositeIn/dsCompositeInHelperClass.py
  host/tests/L3_TestCases/dsCompositeIn/dsCompositeIn_L3_testSetup.yml
  host/tests/L3_TestCases/dsCompositeIn/dsCompositeIn_test1_VerifyConnect_Callback.py
  host/tests/L3_TestCases/dsCompositeIn/dsCompositeIn_test2_VerifyStatus_Callback.py
  host/tests/L3_TestCases/dsCompositeIn/dsCompositeIn_test3_ScaleAndVerify_Video.py
  host/tests/L3_TestCases/dsCompositeIn/dsCompositeIn_test4_VerifySignal_Callback.py
  host/tests/configs/deviceConfig.yml
  host/tests/dsClasses/dsCompositeIn.py
  host/tests/dsClasses/dsCompositeIn_test_suite.yml
  host/tests/dsCompositeIn_L3_Tests/dsCompositeIn_L3_testSetup.yml
  src/test_l3_dsCompositeIn.c
Labels: L3 Work Element
