Repository rdkcentral/rdk-halif-test-device_settings, pull requests merged in 2025-02, with the labels that each got.

#287 gh #284 L1 dsHdmiIn fix for dsHdmiInScaleVideo validation
  src/test_l1_dsHdmiIn.c
Labels: L1 related issues

#290 gh #283 dsGetMS12AudioProfile,dsGetMS12AudioProfileList fix.
  src/test_l1_dsAudio.c
Labels: L1 related issues

#286 gh #285 L1 dsaudio getaudiodelay fix for Headphone port.
  src/test_l1_dsAudio.c
Labels: L1 related issues

#293 gh #292 dsHdmiIn: call selectPort before scaleVideo and GetCurrentVideoMode
  src/test_l1_dsHdmiIn.c
Labels: bug, IF Updates

#291 Gh #288 ds set dialog enhancement update
  src/test_l1_dsAudio.c
Labels: bug, L1 related issues

#302 gh #301 Updated dsAudio Supported ARC types for disconnected state
  host/tests/dsClasses/dsAudio.py
Labels: bug

#299 gh #294 Modified the callback prints for L3 dsVideoPort_test1
  host/tests/L3_TestCases/dsVideoPort/dsVideoPort_test1_VerifyVideoContent_Format_Callback.py
Labels: bug

#304 gh #303 Adding get allm status in L3
  host/tests/L3_TestCases/dsHdmiIn/dsHdmiIn_test05_AllmChangeCallback_Verify.py
  host/tests/dsClasses/dsHdmiIn.py
  host/tests/dsClasses/dsHdmiIn_testConfig.yml
  src/test_l3_dsHdmiIn.c
Labels: enhancement

#129 gh#100: dsVideoPort: Add L1 and L2 Test cases for ALLM APIs
  docs/pages/dsVideoPort/ds-video-port_High-Level_TestSpec.md
  docs/pages/dsVideoPort/ds-video-port_L2_Low-Level_TestSpecification.md
  skeletons/src/dsVideoPort.c
  src/test_l1_dsVideoPort.c
  src/test_l2_dsVideoPort.c
Labels: L1 related issues, L2 Work Element

#279 gh #277 dsVideoPort L3 for an API dsSetAllmEnabled
  docs/pages/dsVideoPort/ds-video-port_High-Level_TestSpec.md
  docs/pages/dsVideoPort/ds-video-port_L3_Low-Level_TestSpecification.md
  docs/pages/dsVideoPort/ds-video-port_L3_Test-Procedure.md
  host/tests/L3_TestCases/dsVideoPort/dsVideoPort_L3_testSetup.yml
  host/tests/L3_TestCases/dsVideoPort/dsVideoPort_RunAll_L3_SinkTest.py
  host/tests/L3_TestCases/dsVideoPort/dsVideoPort_test10_VerifyALLM_Mode.py
  host/tests/dsClasses/dsVideoPort.py
  host/tests/dsClasses/dsVideoPort_testConfig.yml
  skeletons/src/dsVideoPort.c
  src/test_l3_dsVideoPort.c
Labels: enhancement, L3 Work Element

#306 gh #305 - compilation_error_dsVideoPort
  skeletons/src/dsVideoPort.c
Labels: bug

#339 gh #338: Print test version banner
  Makefile
  src/main.c
Labels: L1 related issues, L2 related issues
