Repository rdkcentral/rdk-halif-test-device_settings, pull requests merged in 2025-04, with the labels that each got.

#383 gh #375 update latest utraft, python raft and read me version
  README.md
  host/install.sh
Labels: enhancement

#384 gh #363 dsAudio dsGetAssociatedAudioMixing error code mismatch
  src/test_l1_dsAudio.c
Labels: bug, L1 related issues

#389 gh #366 Adding edid versions in yaml file.
  host/tests/dsClasses/dsHdmiIn.py
  profiles/sink/Sink_HDMIIN.yaml
Labels: bug

#399 gh398 dsHost L3 test suite failed to run as parameter is missing for dsHostClass
  host/tests/L3_TestCases/dsHost/dsHost_test1_VerifyTemperature.py
Labels: bug
