Repository rdkcentral/rdk-halif-test-device_settings, pull requests merged in 2025-05, with the labels that each got.

#390 gh #343 move to L3 Allm Testcases to display
  docs/pages/dsDisplay/ds-display-L2-Low-Level_TestSpec.md
  docs/pages/dsDisplay/ds-display-high-Level_TestSpec.md
  docs/pages/dsDisplay/ds-display_L3_TestProcedure.md
  docs/pages/dsVideoPort/ds-video-port_L3_Test-Procedure.md
  host/tests/L3_TestCases/dsDisplay/dsDisplay_test07_VerifyALLM_Mode.py
  host/tests/L3_TestCases/dsVideoPort/dsVideoPort_RunAll_L3_SinkTest.py
  host/tests/dsClasses/dsDisplay.py
  host/tests/dsClasses/dsDisplay_testConfig.yml
  host/tests/dsClasses/dsVideoPort.py
  host/tests/dsClasses/dsVideoPort_testConfig.yml
  src/test_l3_dsDisplay.c
Labels: enhancement

#410 PR #gh 406 Fix hdmiport initialization
  src/test_l2_dsHdmiIn.c
Labels: bug

#402 PR gh #393 : Fix variable initialization in test cases
  src/test_l1_dsAudio.c
  src/test_l1_dsDisplay.c
  src/test_l2_dsAudio.c
Labels: bug

#409 issue394 l1 dsvideoport is display connected
  src/test_l1_dsVideoPort.c
Labels: bug, L1 related issues

#414 Add l3 avi info frame apis on display
  docs/pages/dsDisplay/ds-display-high-Level_TestSpec.md
  docs/pages/dsDisplay/ds-display_L3_TestProcedure.md
  host/tests/L3_TestCases/dsDisplay/dsDisplay_L3_Runall_Sink.py
  host/tests/L3_TestCases/dsDisplay/dsDisplay_test05_AVIContentTypeVerificationTest.py
  host/tests/L3_TestCases/dsDisplay/dsDisplay_test06_AVIScanInfoVerificationTest.py
  host/tests/dsClasses/dsDisplay.py
  host/tests/dsClasses/dsDisplay_testConfig.yml
  src/test_l3_dsDisplay.c
Labels: L3 Work Element

#418 gh407 l3 VRR C-test
  skeletons/src/dsHdmiIn.c
  src/test_l3_dsHdmiIn.c
Labels: enhancement, L3 Work Element

#428 gh #427 Update test_l3_dsHdmiIn.c
  src/test_l3_dsHdmiIn.c
Labels: bug

#425 gh#424 replace dsAVICONTENT_TYPE_INVALID with dsAVICONTENT_TYPE_NOT_SIGNALLED in HDMI Input test
  host/tests/L3_TestCases/dsHdmiIn/dsHdmiIn_test07_AVIChangeCallback_Verify.py
  host/tests/dsClasses/dsHdmiIn.py
Labels: bug
