Repository rdkcentral/rdk-halif-test-device_settings, pull requests merged in 2025-03, with the labels that each got.

#310 gh#308: Added Python files to test dsAudio dsVideo L1 and L2
  docs/pages/dsAudio/ds-audio_L1_L2_TestProcedure.md
  docs/pages/dsVideoDevice/ds-video-device_L1_L2_TestProcedure.md
  host/tests/L1_L2_TestCases/dsAudio/dsAudio_L1_L2_testSetup.yml
  host/tests/L1_L2_TestCases/dsAudio/dsAudio_L1_L2_tests.py
  host/tests/L1_L2_TestCases/dsVideoDevice/dsVideoDevice_L1_L2_testSetup.yml
  host/tests/L1_L2_TestCases/dsVideoDevice/dsVideoDevice_L1_L2_tests.py
  host/tests/L3_TestCases/dsAudio/dsAudioHelperClass.py
  host/tests/L3_TestCases/dsVideoDevice/dsVideoDeviceHelperClass.py
  host/tests/dsClasses/dsAudio.py
  host/tests/dsClasses/dsAudio_testConfig.yml
  host/tests/dsClasses/dsVideoDevice.py
  host/tests/dsClasses/dsVideoDevice_testConfig.yml
  src/test_l1_dsAudio.c
  src/test_l1_dsVideoDevice.c
  src/test_l2_dsAudio.c
  src/test_l2_dsVideoDevice.c
Labels: documentation, enhancement, L1 related issues, L2 related issues

#349 gh #345 Added python files to test dsFPD L1 and L2
  docs/pages/dsFPD/ds-front-panel-display_L1_L2_TestProcedure.md
  host/tests/L1_L2_TestCases/dsFPD/dsFPD_L1_L2_testSetup.yml
  host/tests/L1_L2_TestCases/dsFPD/dsFPD_L1_L2_tests.py
  host/tests/L3_TestCases/dsFPD/dsFPDHelperClass.py
  host/tests/dsClasses/dsFPD.py
  host/tests/dsClasses/dsFPD_testConfig.yml
  src/test_l1_dsFPD.c
  src/test_l2_dsFPD.c
Labels: enhancement

#355 gh #351 Added python files to test dsVideoPort L1 and L2
  docs/pages/dsVideoPort/ds-video-port_L1_L2_TestProcedure.md
  host/tests/L1_L2_TestCases/dsVideoPort/dsVideoPort_L1_L2_testSetup.yml
  host/tests/L1_L2_TestCases/dsVideoPort/dsVideoPort_L1_L2_tests.py
  host/tests/L3_TestCases/dsVideoPort/dsVideoPortHelperClass.py
  host/tests/dsClasses/dsVideoPort.py
  host/tests/dsClasses/dsVideoPort_testConfig.yml
  src/test_l1_dsVideoPort.c
  src/test_l2_dsVideoPort.c
Labels: enhancement

#358 gh #352 Adding L1 L2 hdmiin python environment.
  docs/pages/dsHDMIIn/ds-hdmi-in_L1_L2_TestProcedure.md
  host/tests/L1_L2_TestCases/dsHdmiIn/dsHdmiIn_L1_L2_testSetup.yml
  host/tests/L1_L2_TestCases/dsHdmiIn/dsHdmiIn_L1_L2_tests.py
  host/tests/dsClasses/dsHdmiIn.py
  host/tests/dsClasses/dsHdmiIn_testConfig.yml
  src/test_l1_dsHdmiIn.c
  src/test_l2_dsHdmiIn.c
Labels: documentation, enhancement, L1 related issues, L2 related issues

#350 gh #346 Added python files to test dsDisplay L1 and L2
  docs/pages/dsDisplay/ds-display_L1_L2_TestProcedure.md
  host/tests/L1_L2_TestCases/dsDisplay/dsDisplay_L1_L2_testSetup.yml
  host/tests/L1_L2_TestCases/dsDisplay/dsDisplay_L1_L2_tests.py
  host/tests/L3_TestCases/dsDisplay/dsDisplayHelperClass.py
  host/tests/dsClasses/dsDisplay.py
  host/tests/dsClasses/dsDisplay_testConfig.yml
  src/test_l1_dsDisplay.c
  src/test_l2_dsDisplay.c
Labels: enhancement

#362 gh #354 dsHost Python L1 L2 Automation
  docs/pages/dsHost/ds-host_L1_L2_TestProcedure.md
  host/tests/L1_L2_TestCases/dsHost/dsHost_L1_L2_testSetup.yml
  host/tests/L1_L2_TestCases/dsHost/dsHost_L1_L2_tests.py
  host/tests/dsClasses/dsHost.py
Labels: enhancement

#342 gh #341 L3 dsDisplay event callbacks matchcase update
  host/tests/L3_TestCases/dsDisplay/dsDisplay_test01_VerifyDisplayConnectCallBackTest.py
  host/tests/dsClasses/dsDisplay.py
Labels: bug

#313 issue309 l1 l2 nullcheck display videoport
  src/test_l1_dsDisplay.c
  src/test_l1_dsVideoPort.c
  src/test_l2_dsDisplay.c
  src/test_l2_dsVideoPort.c
Labels: bug, L1 related issues, L2 related issues

#372 gh #347 Removeinvalid handle check
  src/test_l1_dsAudio.c
Labels: bug

#344 gh #322 l1l2 audio null check validation.
  src/test_l2_dsAudio.c
Labels: bug, L1 related issues, L2 related issues

#371 gh #369 dsAudio L3 segmentation fault in MS12AudioProfile
  src/test_l3_dsAudio.c
Labels: bug, L3 Work Element

#381 gh #380: support for step result dump
  host/tests/L1_L2_TestCases/dsAudio/dsAudio_L1_L2_tests.py
  host/tests/L1_L2_TestCases/dsCompositeIn/dsCompositeIn_L1_L2_tests.py
  host/tests/L1_L2_TestCases/dsDisplay/dsDisplay_L1_L2_testSetup.yml
  host/tests/L1_L2_TestCases/dsDisplay/dsDisplay_L1_L2_tests.py
  host/tests/L1_L2_TestCases/dsFPD/dsFPD_L1_L2_testSetup.yml
  host/tests/L1_L2_TestCases/dsFPD/dsFPD_L1_L2_tests.py
  host/tests/L1_L2_TestCases/dsHdmiIn/dsHdmiIn_L1_L2_testSetup.yml
  host/tests/L1_L2_TestCases/dsHdmiIn/dsHdmiIn_L1_L2_tests.py
  host/tests/L1_L2_TestCases/dsHost/dsHost_L1_L2_testSetup.yml
  host/tests/L1_L2_TestCases/dsHost/dsHost_L1_L2_tests.py
  host/tests/L1_L2_TestCases/dsVideoDevice/dsVideoDevice_L1_L2_tests.py
  host/tests/L1_L2_TestCases/dsVideoPort/dsVideoPort_L1_L2_tests.py
  host/tests/dsClasses/dsAudio.py
  host/tests/dsClasses/dsCompositeIn.py
  host/tests/dsClasses/dsDisplay.py
  host/tests/dsClasses/dsDisplay_testConfig.yml
  host/tests/dsClasses/dsFPD.py
  host/tests/dsClasses/dsHdmiIn.py
  host/tests/dsClasses/dsHdmiIn_testConfig.yml
  host/tests/dsClasses/dsHost.py
  host/tests/dsClasses/dsVideoDevice.py
  host/tests/dsClasses/dsVideoPort.py
  src/test_l1_dsDisplay.c
  src/test_l1_dsHdmiIn.c
  src/test_l1_dsHost.c
Labels: bug, enhancement

#378 gh #377 L1 dsAudio primary secondary language update to lowercase
  src/test_l1_dsAudio.c
Labels: bug

#382 gh #379 type error fix while running audio output mode
  profiles/sink/Sink_AudioSettings.yaml
Labels: bug
